### ISSUE TITLE
Question: How about Nav 2013-2018

### ISSUE THREAD

**Issue by dkorinets** [KirillCheremisin/Nav2009ObjectManager#2]
How about Nav 2013-2018? Do you have a similar solution? Or you are using ps1 scripts?

**Comment by KirillCheremisin** [comment]
Hello @dkorinets!
In the case of Dynamics NAV 2018, we use PowerShell scripts in our team.

I suggest you look through [these scripts](https://github.com/waldo1001/Cloud.Ready.Software.PowerShell).
In case it doesn't fit you for some reasons, the best idea is to use standard scripts or something based on the standard.
